to-do app deployment

diff --git a/.github/workflows/src.yml b/.github/workflows/src.yml
--- a/.github/workflows/src.yml
+++ b/.github/workflows/src.yml
@@ -43,26 +43,31 @@ jobs:
       id: determine-client-tag
       run: echo "::set-output name=client_tag_value::v$(( $(cat client_tag_counter.txt) + 1 ))"
 
-    - name: Build and tag client Docker image
+    - name: Build, tag and push the client docker image
       if: contains(github.event_path, 'src/client/')
       run: |
         docker build -t $ECR_REPO_URL/client:${{ steps.determine-client-tag.outputs.client_tag_value }} ./src/client
-        echo ${{ steps.determine-client-tag.outputs.client_tag_value }} > client_tag_counter.txt
+        if [ $? -eq 0 ]; then
+          docker push $ECR_REPO_URL/client:${{ steps.determine-client-tag.outputs.client_tag_value }}
+          echo ${{ steps.determine-client-tag.outputs.client_tag_value }} > client_tag_counter.txt
+        else
+          echo "Build failed."
+          exit 1
+        fi
 
     - name: Determine server image tag
       id: determine-server-tag
       run: echo "::set-output name=server_tag_value::v$(( $(cat server_tag_counter.txt) + 1 ))"
 
-    - name: Build and tag server Docker image
+    - name: Build, tag and push the server docker image
       if: contains(github.event_path, 'src/server/')
       run: |
-        docker build -t $ECR_REPO_URL/server:${{ steps.determine-server-tag.outputs.server_tag_value }} ./src/server
-        echo ${{ steps.determine-server-tag.outputs.server_tag_value }} > server_tag_counter.txt
-
-    - name: Push client Docker image to ECR
-      if: success() && steps.determine-client-tag.outputs.client_tag_value
-      run: docker push $ECR_REPO_URL/client:${{ steps.determine-client-tag.outputs.client_tag_value }}
-
-    - name: Push server Docker image to ECR
-      if: success() && steps.determine-server-tag.outputs.server_tag_value
-      run: docker push $ECR_REPO_URL/server:${{ steps.determine-server-tag.outputs.server_tag_value }}
+        docker build -t $ECR_REPO_URL/server:${{ steps.determine-client-tag.outputs.server_tag_value }} ./src/server
+        if [ $? -eq 0 ]; then
+          docker push $ECR_REPO_URL/server:${{ steps.determine-client-tag.outputs.server_tag_value }}
+          echo ${{ steps.determine-client-tag.outputs.server_tag_value }} > server_tag_counter.txt
+        else
+          echo "Build failed."
+          exit 1
+        fi
+    
