revised pipelines for to-do app deployment

diff --git a/.github/workflows/src.yml b/.github/workflows/src.yml
--- a/.github/workflows/src.yml
+++ b/.github/workflows/src.yml
@@ -2,70 +2,73 @@ name: Build Docker Images
 
 env:
   ECR_REPO_URL: ${{ vars.ECR_REPOSITORY_URL }}
+  REGION: ${{ vars.AWS_REGION }} 
 
 on:
   push:
-    # paths:
-    #   - 'src/client/**'
-    #   - 'src/server/**'
     branches:
       - dev
-#   workflow_dispatch:
-#     inputs:
-#       build_response:
-#         description: 'Confirm Build'
-#         required: true
-#         default: 'no'
 
 jobs:
   build_and_push:
     runs-on: ubuntu-latest
 
     steps:
-    - name: Checkout repository
-      uses: actions/checkout@v2
+      - name: Checkout repository
+        uses: actions/checkout@v2
 
-    - name: Set up Docker Buildx
-      uses: docker/setup-buildx-action@v1
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v1
 
-    - name: Setup AWS credentials
-      uses: aws-actions/configure-aws-credentials@v4
-      with:
-        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-        aws-region: ${{ vars.AWS_REGION }}
+      - name: Setup AWS credentials
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region: $REGION
 
-    - name: Login to Amazon ECR
-      id: login-ecr
-      uses: aws-actions/amazon-ecr-login@v2
+      - name: Login to Amazon ECR
+        id: login-ecr
+        uses: aws-actions/amazon-ecr-login@v2
 
-    - name: Determine client image tag
-      id: determine-client-tag
-      run: echo "::set-output name=client_tag_value::v$(( $(cat ./src/client/client.txt) + 1 ))"
-    
-    - name: Build, tag and push the client docker image
-      run: |
-        docker build -t $ECR_REPO_URL:client-v${{ steps.determine-client-tag.outputs.client_tag_value }} ./src/client
-        if [ $? -eq 0 ]; then
-          docker push $ECR_REPO_URL:client-v${{ steps.determine-client-tag.outputs.client_tag_value }}
-          echo $(( $(cat ./src/client/client.txt) + 1 )) > $GITHUB_WORKSPACE/src/client/client.txt
-        else
-          echo "Build failed."
-          exit 1
-        fi
-    
-    - name: Determine server image tag
-      id: determine-server-tag
-      run: echo "::set-output name=server_tag_value::v$(( $(cat ./src/server/server.txt) + 1 ))"
-    
-    - name: Build, tag and push the server docker image
-      run: |
-        docker build -t $ECR_REPO_URL:server-v${{ steps.determine-server-tag.outputs.server_tag_value }} ./src/server
-        if [ $? -eq 0 ]; then
-          docker push $ECR_REPO_URL:server-v${{ steps.determine-server-tag.outputs.server_tag_value }}
-          echo $(( $(cat ./src/server/server.txt) + 1 )) > $GITHUB_WORKSPACE/src/server/server.txt
-        else
-          echo "Build failed."
-          exit 1
-        fi
-    
+      - name: Retrieve previous client and server tag values
+        uses: actions/download-artifact@v2
+        with:
+          name: tag-values
+          path: artifacts
+
+      - name: Determine client image tag
+        id: determine-client-tag
+        run: echo "::set-output name=client_tag_value::$(( $(cat ./src/client/client.txt) + 1 ))"
+
+      - name: Determine server image tag
+        id: determine-server-tag
+        run: echo "::set-output name=server_tag_value::v$(( $(cat ./src/server/server.txt) + 1 ))"
+
+      - name: Build, tag and push the client docker image
+        run: |
+          docker build -t $ECR_REPO_URL:client-v${{ steps.determine-client-tag.outputs.client_tag_value }} ./src/client
+          if [ $? -eq 0 ]; then
+            docker push $ECR_REPO_URL:client-v${{ steps.determine-client-tag.outputs.client_tag_value }}
+            echo $(( $(cat ./src/client/client.txt) + 1 )) > ./src/client/client.txt
+          else
+            echo "Build failed."
+            exit 1
+          fi
+
+      - name: Build, tag and push the server docker image
+        run: |
+          docker build -t $ECR_REPO_URL:server-${{ steps.determine-server-tag.outputs.server_tag_value }} ./src/server
+          if [ $? -eq 0 ]; then
+            docker push $ECR_REPO_URL:server-${{ steps.determine-server-tag.outputs.server_tag_value }}
+            echo $(( $(cat ./src/server/server.txt) + 1 )) > ./src/server/server.txt
+          else
+            echo "Build failed."
+            exit 1
+          fi
+
+      - name: Save updated tag values as artifact
+        uses: actions/upload-artifact@v2
+        with:
+          name: tag-values
+          path: artifacts
